periodics:
# Periodic jobs for cert-manager/cert-manager

- name: periodic-cert-manager-release-next-unit-test
  interval: 6h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: cert-manager
    repo: cert-manager
    base_ref: main
    path_alias: github.com/cert-manager/cert-manager
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  annotations:
    testgrid-dashboards: cert-manager-periodic
    testgrid-tab-name: release-next-unit-test
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs unit tests against the latest cert-manager main branch every 6 hours
  spec:
    containers:
    - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/golang-dind:20231010-9df2e5e-1.21
      args:
      - runner
      - make
      - test
      resources:
        requests:
          cpu: 4
          memory: 6Gi

- name: periodic-cert-manager-release-next-e2e-v1-27
  interval: 12h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: cert-manager
    repo: cert-manager
    base_ref: main
    path_alias: github.com/cert-manager/cert-manager
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  annotations:
    testgrid-dashboards: cert-manager-periodic
    testgrid-tab-name: release-next-e2e-v1-27
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs e2e tests against the latest cert-manager main branch on Kubernetes v1.27 every 12 hours
  spec:
    containers:
    - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/golang-dind:20231010-9df2e5e-1.21
      args:
      - runner
      - make
      - e2e-ci
      env:
      - name: K8S_VERSION
        value: "1.27"
      resources:
        requests:
          cpu: 6
          memory: 12Gi

- name: periodic-cert-manager-release-next-e2e-v1-28
  interval: 12h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: cert-manager
    repo: cert-manager
    base_ref: main
    path_alias: github.com/cert-manager/cert-manager
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  annotations:
    testgrid-dashboards: cert-manager-periodic
    testgrid-tab-name: release-next-e2e-v1-28
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs e2e tests against the latest cert-manager main branch on Kubernetes v1.28 every 12 hours
  spec:
    containers:
    - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/golang-dind:20231010-9df2e5e-1.21
      args:
      - runner
      - make
      - e2e-ci
      env:
      - name: K8S_VERSION
        value: "1.28"
      resources:
        requests:
          cpu: 6
          memory: 12Gi
