clusters:
- gke: projects/cert-manager-tests-trusted/locations/europe-west1-b/clusters/prow-trusted
  name: prow-trusted
  # Increased duration to 72h to reduce frequency of credential rotation
  duration: 72h
  kubernetesSecret:
    name: kubeconfig-prow-trusted
    namespace: default

- gke: projects/cert-manager-tests-untrusted/locations/europe-west1-b/clusters/prow-untrusted
  name: default
  # Reduced duration to 24h for more frequent rotation in untrusted cluster
  duration: 24h
  kubernetesSecret:
    name: kubeconfig-prow-untrusted
    namespace: default
